apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.dndn24.kro.kr
      secretName: dndn24-tls
  rules:
    - host: www.dndn24.kro.kr
      http:
        paths:
          - path: /api/msa
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8088
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
