apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-sync-cronjob
  namespace: batch
spec:
  schedule: "30 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: worker-sync-batch
              image: seungwoo0128/dndn-batch:2.1
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: backend-config
              resources:
                requests:
                  cpu: "200m"
                  memory: "512Mi"
                limits:
                  cpu: "1000m"
                  memory: "1024Mi"
