server:
  port: ${GATEWAY_PORT:8088}

spring:
  application:
    name: dndn-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: document-management-api
              uri: ${DOCUMENT_MANAGEMENT_SERVICE_URI:lb://DNDN-DOCUMENT-MANAGEMENT}
              predicates:
                - Path=/api/msa/document-management/**
              filters:
                - RewritePath=/api/msa/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: info
    org.example: info
